Repository GlueOps/k3d, pull requests merged in 2024-05, with the labels that each got.

#6 feat: setting k8s version explicitly to 1.28.X
  k3d-config.yaml
Labels: enhancement, include-in-release-notes, minor

#7 Feature/configure node machine
  README.md
  add-machineid.sh
Labels: documentation, enhancement, include-in-release-notes, minor, patch, Review effort [1-5]: 2

#8 feat: adding another node for glueops platform. Specifically for argocd-application-controller
  k3d-config.yaml
Labels: enhancement, include-in-release-notes, minor, Review effort [1-5]: 2

#11 feat: migrating to tailscale based registry and planning to delete th…
  k3d-config.yaml
Labels: enhancement, include-in-release-notes, minor

#12 fix: domain for registry
  k3d-config.yaml
Labels: include-in-release-notes, patch
